[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python', 'go', 'typescript',  'typescriptreact','dockerfile', 'javascript', 'javascript.jsx', 'javascriptreact', 'cpp', 'rust', 'java', 'kotlin']
depends = ['async.vim']
hook_source = '''
  source ~/.config/nvim/plugins/lsp.vim
'''

[[plugins]]
repo = 'Ttayu/deoplete-vim-lsp'
depends = ['deoplete.nvim']
on_ft = ['python', 'go', 'typescript',  'typescriptreact','dockerfile', 'javascript', 'javascript.jsx', 'javascriptreact', 'cpp', 'rust', 'java', 'kotlin']
