[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python', 'go', 'typescript',  'typescriptreact','dockerfile', 'javascript', 'javascript.jsx', 'javascriptreact', 'cpp', 'rust', 'java', 'kotlin', 'r']
hook_source = '''
  source ~/.config/nvim/plugins/lsp.vim
  " set foldlevel=100
  " set foldmethod=expr
  "  \ foldexpr=lsp#ui#vim#folding#foldexpr()
  "  \ foldtext=lsp#ui#vim#folding#foldtext()
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim']
on_ft = ['python', 'go', 'typescript',  'typescriptreact','dockerfile', 'javascript', 'javascript.jsx', 'javascriptreact', 'cpp', 'rust', 'java', 'kotlin', 'r']
