[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_source = '''
  let g:fruzzy#sortonempty = 0
'''
hook_post_update = '''
  call fruzzy#install()
'''

# linter実行プラグイン
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  source ~/.config/nvim/plugins/ale.vim
'''

# vim用補完フレームワーク
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
  source ~/.config/nvim/plugins/deoplete.vim
# '''

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['vim-snippets', 'neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/neosnippet.vim
'''

# file viewer
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/defx.vim
'''
hook_source = '''
  call defx#custom#option('_', {
        \ 'toggle': 1,
        \ 'split': 'vertical',
        \ 'winwidth': 20,
        \ 'direction': 'topleft'
        \ })
  call defx#custom#column('mark', {
        \ 'readonly_icon': '✗',
        \ 'selected_icon': '✓',
        \ })
  call defx#custom#column('filename', {
        \ 'directory_icon': '',
        \ 'opened_icon': '▼',
        \ 'root_icon': ' ',
        \ }) 
'''

# ファイルランチャー
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_source = '''
  source ~/.config/nvim/plugins/denite_source.vim
'''
hook_add = '''
  source ~/.config/nvim/plugins/denite_add.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
# on_if = 1
on_source = ['denite.nvim']

# git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.config/nvim/plugins/quickrun.vim
'''

# gtagsを非同期で自動更新
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = ['python', 'go','vim']
hook_add = '''
  " ctags, gtagsを自動で生成，更新
  let g:gen_tags#ctags_auto_gen = 1
  let g:gen_tags#gtags_auto_gen = 1
'''

# syntax
# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

# vim-script
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']
depends = ['deoplete.nvim']
