[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
lua << EOF
  require("tokyonight").setup({
    style = "night",
    transparent = true,
  })
EOF
'''

# ウィンドウサイズの変更
[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
lua_add = '''
  require('impatient')
'''
