# typescript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'Ttayu/vim-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'fleischie/vim-styled-components'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'Valloric/MatchTagAlways'
on_ft = ['html', 'javascript', 'typescript']
hook_source = '''
  let g:mta_filetypes = {
        \ 'html': 1,
        \ 'javascript': 1,
        \ 'typescript': 1,
        \ }
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript', 'typescript']
hook_add = '''
  let g:user_emmet_install_global = 0
  let g:user_emmet_settings = {
       \ 'javascript': {
       \   'extends': 'jsx',
       \ },
       \ 'typescript': {
       \   'extends': 'jsx',
       \ },
       \}
  autocmd FileType html,css,javascript,javascript.jsx,typescript EmmetInstall
'''

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql', 'qql', 'Relay.QL', 'js', 'typescript']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']
