[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = 'BufRead'
hook_source = '''
  source ~/.config/nvim/plugins/lsp.vim
  " set foldlevel=100
  " set foldmethod=expr
  "  \ foldexpr=lsp#ui#vim#folding#foldexpr()
  "  \ foldtext=lsp#ui#vim#folding#foldtext()
'''

[[plugins]]
repo = 'machakann/vim-lsp-julia'
on_ft = ['julia']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
