[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim', 'lspsaga.nvim','ddc.vim']
on_event = ['BufRead', 'InsertEnter']
hook_source = '''
  source ~/.config/nvim/plugins/lsp.lua
'''

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'


[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'glepnir/lspsaga.nvim'
depends = 'nvim-web-devicons'

[[plugins]]
repo = 'Ttayu/nvim-lsp-autoimport'
on_source = ['nvim-lspconfig', 'pum.vim']
lua_source = '''
  require("autoimport")
'''
