# go
[[plugins]]
repo = 'zchee/nvim-go'
build = 'make'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#source#go#gocode_binary = $GOPATH . '/bin/gocode'
'''
