# python
# virtualenvのパス自動追加
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

# pep8準拠のインデント
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

# deopleteのpython用プラグイン
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim', 'vim-virtualenv']
on_ft = ['python']
