[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_source = '''
  let g:fruzzy#sortonempty = 0
'''
hook_post_update = '''
  call fruzzy#install()
'''

# linter実行プラグイン
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  source ~/.config/nvim/plugins/ale.vim
'''

# vim用補完フレームワーク
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
on_source = ['denite.nvim']
hook_source = '''
  source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# file viewer
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  nnoremap <silent> ,n :<C-u>Defx<CR>
'''
hook_source = '''
  source ~/.config/nvim/plugins/defx.vim
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']

# ファイルランチャー
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  source ~/.config/nvim/plugins/denite_add.vim
'''
hook_source = '''
  source ~/.config/nvim/plugins/denite_source.vim
'''

# git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.config/nvim/plugins/quickrun.vim
'''

# gtagsを非同期で自動更新
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
  " ctags, gtagsを自動で生成，更新
  let g:gen_tags#ctags_auto_gen = 1
'''

# viewer for LSP symbols
[[plugins]]
repo = 'liuchengxu/vista.vim'
depends = ['vim-lsp']
hook_add = '''
  let g:vista_close_on_jump = 1
  let g:vista#renderer#enable_icon = 1
  let g:vista_default_executive = 'vim_lsp'
  nnoremap <silent> <leader>v :<C-u>Vista!!<CR>
  autocmd vimrc BufEnter * if (&filetype == 'vista' || &filetype == 'vista_kind') && winnr('$') == 1 | q | endif
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

# syntax
# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

# vim-script
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

# cmake
[[plugins]]
repo = 'deoplete-plugins/deoplete-clang'
on_ft = ['cmake']
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
  let g:deoplete#sources#clang#clang_header = '/Library/Developer/CommandLineTools/usr/lib/clang'
'''

# zsh
[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'
on_ft = ['zsh', 'sh']

# latex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
  let g:vimtex_compiler_latexmk_engines = {'_': '-pdfdvi'}
  let g:tex_flavor = 'latex'
  let g:vimtex_quickfix_open_on_warning = 0
  if has('mac')
    let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
    let g:vimtex_view_general_options = '@line @pdf @tex'
  else
    let g:vimtex_view_general_viewer = 'evince'
  endif
'''

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']
hook_add = """
  autocmd FileType kotlin setlocal sw=4 sts=4 ts=4 et
"""

[[plugins]]
repo = 'ncm2/float-preview.nvim'
on_source = 'deoplete.nvim'
depends = 'context_filetype.vim'
hook_source = '''
  let s:width = 100
  function! s:set_preview_docked()
    if winwidth('%') > s:width
      let g:float_preview#docked = 0
      let g:float_preview#max_width = 60
      let g:float_preview#max_height = 20
    else
      let g:float_preview#docked = 1
      let g:float_preview#max_width = winwidth('%')
      let g:float_preview#max_height = 0
    endif
  endfunction
  call s:set_preview_docked()
  augroup MyFloadPreview
    autocmd!
    autocmd VimResized * call s:set_preview_docked()
  augroup END
'''
