[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-lsp-installer', 'ddc.vim']
on_event = ['BufRead', 'InsertEnter']
hook_source = '''
  source ~/.config/nvim/plugins/lsp.lua
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
