[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim', 'lspsaga.nvim', 'ddc.vim']
on_event = ['BufRead', 'InsertEnter']
hook_source = '''
  source ~/.config/nvim/plugins/lsp.lua
'''

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'


[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvimdev/lspsaga.nvim'
depends = 'nvim-web-devicons'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvimtools/none-ls.nvim'
depends = 'plenary.nvim'
on_source = ['mason.nvim']

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'
on_source = ['mason.nvim', 'null-ls.nvim']

[[plugins]]
repo = 'mfussenegger/nvim-dap'
on_source = ['mason.nvim']

[[plugins]]
repo = 'nvim-neotest/nvim-nio'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_source = ['mason.nvim', 'nvim-dap']
depends = ['nvim-nio']
hook_source = '''
  hi DapBreakpointTextHl guifg=#AA0000
  hi DapStoppedTextHl guifg=#00c853
  source ~/.config/nvim/plugins/dap.lua
'''
