[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = "vim-denops/denops.vim"
on_event = 'CursorHold'

# colorscheme
[[plugins]]
repo = 'folke/tokyonight.nvim'
lua_add = '''
  require("tokyonight").setup({
    style = "night",
    transparent = true,
  })
'''

# ウィンドウサイズの変更
[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
lua_add = '''
  require('impatient')
'''
