# go
[[plugins]] 
repo = 'fatih/vim-go'
on_ft = 'go'
build = ':GoUpdateBinaries'
hook_add = '''
  autocmd FileType go :highlight goErr cterm=bold ctermfg=214 gui=bold guifg=#ffaf00
  autocmd FileType go :match goErr /\<err\>/

  " Specifies the type of list to use for command outputs
  let g:go_list_type = "locationlist"
  let g:go_list_type_commands = {"GoInstall": "quickfix", "GoBuild": "quickfix", "GoTest": "quickfix"}
  let g:go_list_autoclose = 1
  let g:go_list_height = 10

  " disable vim-go default mapping for use vim-lsp
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_textobj_enabled = 0

  " disable it will jump to the first error automatically
  let g:go_jump_to_error = 0

  " disable running build and test command in terminal
  let g:go_term_enabled = 0
  let g:go_term_mode = "split"
  let g:go_term_height = 10
  " let g:go_term_width = 30

  " go highlights
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_types = 1

  " highlight all uses of the identifier under the cursor. |:GoSameIds| automatically
  let g:go_auto_sameids = 0

  " description of the identifer under the cursor.
  let g:go_auto_type_info = 0
  " let g:go_fmt_command = "goimports"

  " let g:go_def_mapping_enabled = 0
  " let g:go_doc_keywordprg_enabled = 0
'''
